"""Selection de l'icone SVG associee a un fichier du directory listing
(retour utilisateur : "incorporer des vrais icones svg").

Module pur (aucune I/O, aucun import externe) : les icones elles-memes
(bytes) sont servies depuis `infrastructure/icons/icon_files.py`, ce
fichier ne choisit qu'un NOM de fichier parmi un ensemble ferme et
connu a l'avance (`ICON_FILENAMES`) - jamais un chemin arbitraire.

Securite (retour utilisateur, recommandation OWASP citee) : un SVG non
fiable peut contenir du script, des gestionnaires d'evenements ou un
`foreignObject` - injecter le contenu SVG directement dans le HTML
(`<div>{{ contenu_svg }}</div>`) executerait ce script. Le modele retenu
ici satisfait les 3 conditions recommandees a la fois :
1. Les icones sont fournies par nous (verifiees, aucun `<script>`/
   gestionnaire d'evenement/`foreignObject` - voir la revue faite avant
   integration), jamais televersees ni modifiables par un utilisateur.
2. Elles vivent dans un repertoire statique du PAQUET Python lui-meme
   (`infrastructure/icons/svg/`), jamais dans l'arborescence servie par
   le site (`project_root`) - aucun utilisateur du serveur ne peut les
   remplacer.
3. Elles sont referencees via `<img src="...">` (dirlisting.py), jamais
   injectees inline dans le HTML - meme un SVG malveillant charge par
   `<img>` ne peut pas executer de script (le navigateur le traite comme
   une image, jamais comme un document HTML/SVG actif).

Selection : MIME type d'abord (formats standards), extension ensuite
(paquets/fichiers systeme dont le MIME type reel est souvent generique -
`application/octet-stream`), puis `unknow.svg` en dernier recours - meme
logique que documentee dans le mapping fourni."""
from __future__ import annotations

from pathlib import PurePosixPath

MIME_ICONS: dict[str, str] = {
    "inode/directory": "folder.svg",
    "application/octet-stream": "unknow.svg",
    "application/x-unknown": "unknow.svg",
    "application/x-binary": "bin.svg",
    "text/plain": "text-generic.svg",
    "text/csv": "csv.svg",
    "text/markdown": "markdown.svg",
    "text/html": "html.svg",
    "text/css": "html.svg",
    "text/javascript": "script.svg",
    "application/javascript": "script.svg",
    "application/json": "json.svg",
    "application/ld+json": "json.svg",
    "application/xml": "xml.svg",
    "text/xml": "xml.svg",
    "application/yaml": "ini.svg",
    "text/yaml": "ini.svg",
    "application/x-yaml": "ini.svg",
    "text/x-ini": "ini.svg",
    "text/x-config": "ini.svg",
    "text/x-readme": "text-generic.svg",
    "text/x-python": "python.svg",
    "text/x-python-script": "python.svg",
    "application/x-python-code": "python.svg",
    "text/x-perl": "perl.svg",
    "application/x-perl": "perl.svg",
    "text/x-php": "php.svg",
    "application/x-php": "php.svg",
    "text/x-ruby": "ruby.svg",
    "application/x-ruby": "ruby.svg",
    "text/x-java-source": "java.svg",
    "text/java": "java.svg",
    "text/x-c": "c++.svg",
    "text/x-c++": "c++.svg",
    "text/x-c++src": "c++.svg",
    "text/x-shellscript": "script.svg",
    "application/x-sh": "script.svg",
    "text/x-lua": "script.svg",
    "text/x-makefile": "script.svg",
    "image/jpeg": "image.svg",
    "image/png": "image.svg",
    "image/gif": "image.svg",
    "image/webp": "image.svg",
    "image/avif": "image.svg",
    "image/apng": "image.svg",
    "image/bmp": "image.svg",
    "image/tiff": "image.svg",
    "image/x-tiff": "image.svg",
    "image/vnd.microsoft.icon": "image.svg",
    "image/x-icon": "image.svg",
    "image/heic": "image.svg",
    "image/heif": "image.svg",
    "image/jxl": "image.svg",
    "image/svg+xml": "vector-image.svg",
    "application/postscript": "postscript.svg",
    "image/x-eps": "postscript.svg",
    "application/illustrator": "drawing.svg",
    "image/x-xcf": "drawing.svg",
    "image/vnd.adobe.photoshop": "drawing.svg",
    "application/pdf": "pdf.svg",
    "application/rtf": "rtf.svg",
    "text/rtf": "rtf.svg",
    "application/epub+zip": "ebook.svg",
    "application/x-fictionbook+xml": "ebook.svg",
    "application/x-mobipocket-ebook": "ebook.svg",
    "application/msword": "word.svg",
    "application/vnd.ms-word": "word.svg",
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document": "word.svg",
    "application/vnd.openxmlformats-officedocument.wordprocessingml.template": "word.svg",
    "application/vnd.ms-excel": "excel.svg",
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": "excel.svg",
    "application/vnd.openxmlformats-officedocument.spreadsheetml.template": "excel-template.svg",
    "application/vnd.ms-powerpoint": "presentation.svg",
    "application/vnd.openxmlformats-officedocument.presentationml.presentation": "presentation.svg",
    "application/vnd.openxmlformats-officedocument.presentationml.template": "powerpoint-template.svg",
    "application/vnd.openxmlformats-officedocument.presentationml.slideshow": "presentation.svg",
    "application/vnd.ms-powerpoint.template.macroEnabled.12": "powerpoint-macro.svg",
    "application/vnd.ms-powerpoint.presentation.macroEnabled.12": "powerpoint-macro.svg",
    "application/vnd.ms-powerpoint.slideshow.macroEnabled.12": "powerpoint-macro.svg",
    "application/msaccess": "ms-access.svg",
    "application/vnd.ms-access": "ms-access.svg",
    "application/vnd.ms-office": "doc.svg",
    "application/onenote": "onenote.svg",
    "application/vnd.ms-onenote": "onenote.svg",
    "application/vnd.ms-publisher": "publisher.svg",
    "application/x-mspublisher": "publisher.svg",
    "text/calendar": "calendar.svg",
    "application/ics": "calendar.svg",
    "application/x-ical": "calendar.svg",
    "application/vnd.ms-xpsdocument": "doc.svg",
    "application/vnd.oasis.opendocument.text": "word.svg",
    "application/vnd.oasis.opendocument.text-template": "word.svg",
    "application/vnd.oasis.opendocument.spreadsheet": "spreadsheet.svg",
    "application/vnd.oasis.opendocument.spreadsheet-template": "spreadsheet.svg",
    "application/vnd.oasis.opendocument.presentation": "presentation.svg",
    "application/vnd.oasis.opendocument.presentation-template": "presentation.svg",
    "application/vnd.oasis.opendocument.graphics": "drawing.svg",
    "application/zip": "package.svg",
    "application/x-zip-compressed": "package.svg",
    "application/gzip": "package.svg",
    "application/x-gzip": "package.svg",
    "application/x-bzip": "package.svg",
    "application/x-bzip2": "package.svg",
    "application/x-xz": "package.svg",
    "application/zstd": "package.svg",
    "application/x-zstd": "package.svg",
    "application/x-7z-compressed": "package.svg",
    "application/vnd.rar": "package.svg",
    "application/x-rar-compressed": "package.svg",
    "application/x-tar": "package.svg",
    "application/x-compress": "package.svg",
    "application/x-lzip": "package.svg",
    "application/x-lzma": "package.svg",
    "application/x-lz4": "package.svg",
    "application/x-archive": "package.svg",
    "application/x-iso9660-image": "iso.svg",
    "application/x-cd-image": "iso.svg",
    "application/x-apple-diskimage": "iso.svg",
    "application/vnd.apple.installer+xml": "package.svg",
    "application/vnd.android.package-archive": "android.svg",
    "application/x-deb": "deb.svg",
    "application/vnd.debian.binary-package": "deb.svg",
    "application/x-rpm": "rpm.svg",
    "application/x-rpm-package": "rpm.svg",
    "application/java-archive": "java.svg",
    "application/x-java-archive": "java.svg",
    "application/x-pkg": "package.svg",
    "application/x-pacman-package": "package.svg",
    "application/vnd.microsoft.portable-executable": "exe.svg",
    "application/x-msdownload": "exe.svg",
    "application/x-dosexec": "exe.svg",
    "application/x-elf": "exe.svg",
    "application/x-executable": "exe.svg",
    "application/wasm": "exe.svg",
    "audio/mpeg": "audio.svg",
    "audio/mp3": "audio.svg",
    "audio/aac": "audio.svg",
    "audio/flac": "audio.svg",
    "audio/ogg": "audio.svg",
    "audio/opus": "audio.svg",
    "audio/wav": "audio.svg",
    "audio/x-wav": "audio.svg",
    "audio/webm": "audio.svg",
    "audio/mp4": "audio.svg",
    "audio/x-m4a": "audio.svg",
    "audio/midi": "midi.svg",
    "audio/x-midi": "midi.svg",
    "audio/x-ms-wma": "audio.svg",
    "video/mp4": "video.svg",
    "video/mpeg": "video.svg",
    "video/ogg": "video.svg",
    "video/webm": "video.svg",
    "video/x-msvideo": "video.svg",
    "video/quicktime": "video.svg",
    "video/x-matroska": "video.svg",
    "video/x-flv": "video.svg",
    "video/3gpp": "video.svg",
    "video/3gpp2": "video.svg",
    "video/x-ms-wmv": "video.svg",
    "font/woff": "font.svg",
    "font/woff2": "font.svg",
    "font/ttf": "font.svg",
    "font/otf": "font.svg",
    "application/font-woff": "font.svg",
    "application/vnd.ms-fontobject": "font.svg",
    "application/x-font-ttf": "font.svg",
    "application/x-font-opentype": "font.svg",
    "application/pkcs12": "key.svg",
    "application/x-pkcs12": "key.svg",
    "application/pkcs8": "key.svg",
    "application/x-pem-file": "pem-key.svg",
    "application/pem-certificate-chain": "pem-key.svg",
    "application/x-x509-ca-cert": "pem-key.svg",
    "application/pkix-cert": "pem-key.svg",
    "application/pkix-crl": "crypt.svg",
    "application/pgp-encrypted": "crypt.svg",
    "application/pgp-keys": "key.svg",
    "application/pgp-signature": "crypt.svg",
    "application/pkcs7-mime": "crypt.svg",
    "application/pkcs7-signature": "crypt.svg",
    "application/sql": "csv.svg",
    "application/x-sql": "csv.svg",
    "application/x-sqlite3": "spreadsheet.svg",
    "application/vnd.sqlite3": "spreadsheet.svg",
    "application/x-bittorrent": "torrent.svg",
    "application/x-bittorrent-metadata": "torrent.svg",
}

EXTENSION_ICONS: dict[str, str] = {
    ".7z": "package.svg",
    ".zip": "package.svg",
    ".tar": "package.svg",
    ".gz": "package.svg",
    ".tgz": "package.svg",
    ".bz": "package.svg",
    ".bz2": "package.svg",
    ".xz": "package.svg",
    ".zst": "package.svg",
    ".lz": "package.svg",
    ".lz4": "package.svg",
    ".lzma": "package.svg",
    ".rar": "package.svg",
    ".deb": "deb.svg",
    ".rpm": "rpm.svg",
    ".pkg": "package.svg",
    ".pkg.tar": "package.svg",
    ".pkg.tar.zst": "package.svg",
    ".pkg.tar.xz": "package.svg",
    ".apk": "android.svg",
    ".exe": "exe.svg",
    ".msi": "exe.svg",
    ".dll": "bin.svg",
    ".so": "bin.svg",
    ".so.1": "bin.svg",
    ".bin": "bin.svg",
    ".elf": "exe.svg",
    ".appimage": "exe.svg",
    ".jar": "java.svg",
    ".war": "java.svg",
    ".txt": "text-generic.svg",
    ".log": "text-generic.svg",
    ".md": "markdown.svg",
    ".markdown": "markdown.svg",
    ".html": "html.svg",
    ".htm": "html.svg",
    ".css": "html.svg",
    ".js": "script.svg",
    ".mjs": "script.svg",
    ".cjs": "script.svg",
    ".json": "json.svg",
    ".jsonl": "json.svg",
    ".xml": "xml.svg",
    ".xhtml": "html.svg",
    ".yaml": "ini.svg",
    ".yml": "ini.svg",
    ".ini": "ini.svg",
    ".cfg": "ini.svg",
    ".conf": "ini.svg",
    ".config": "ini.svg",
    ".toml": "ini.svg",
    ".env": "key.svg",
    ".py": "python.svg",
    ".pyw": "python.svg",
    ".pyi": "python.svg",
    ".pl": "perl.svg",
    ".pm": "perl.svg",
    ".pod": "podcoast.svg",
    ".php": "php.svg",
    ".php3": "php.svg",
    ".php4": "php.svg",
    ".php5": "php.svg",
    ".phtml": "php.svg",
    ".rb": "ruby.svg",
    ".rake": "ruby.svg",
    ".java": "java.svg",
    ".class": "java.svg",
    ".c": "c++.svg",
    ".h": "c++.svg",
    ".cc": "c++.svg",
    ".cpp": "c++.svg",
    ".cxx": "c++.svg",
    ".hpp": "c++.svg",
    ".hh": "c++.svg",
    ".hxx": "c++.svg",
    ".sh": "script.svg",
    ".bash": "script.svg",
    ".zsh": "script.svg",
    ".fish": "script.svg",
    ".bat": "script.svg",
    ".cmd": "script.svg",
    ".ps1": "script.svg",
    ".lua": "script.svg",
    ".vim": "script.svg",
    ".pdf": "pdf.svg",
    ".rtf": "rtf.svg",
    ".epub": "ebook.svg",
    ".mobi": "ebook.svg",
    ".azw": "ebook.svg",
    ".azw3": "ebook.svg",
    ".doc": "word.svg",
    ".docx": "word.svg",
    ".docm": "word.svg",
    ".dot": "word.svg",
    ".dotx": "word.svg",
    ".xls": "excel.svg",
    ".xlsx": "excel.svg",
    ".xlsm": "excel.svg",
    ".xlt": "excel-template.svg",
    ".xltx": "excel-template.svg",
    ".xltm": "excel-template.svg",
    ".csv": "csv.svg",
    ".ods": "spreadsheet.svg",
    ".ots": "spreadsheet.svg",
    ".ppt": "presentation.svg",
    ".pptx": "presentation.svg",
    ".pps": "presentation.svg",
    ".ppsx": "presentation.svg",
    ".pot": "powerpoint-template.svg",
    ".potx": "powerpoint-template.svg",
    ".potm": "powerpoint-macro.svg",
    ".pptm": "powerpoint-macro.svg",
    ".ppsm": "powerpoint-macro.svg",
    ".accdb": "ms-access.svg",
    ".mdb": "ms-access.svg",
    ".one": "onenote.svg",
    ".onepkg": "onenote.svg",
    ".odt": "word.svg",
    ".odp": "presentation.svg",
    ".odg": "drawing.svg",
    ".ics": "calendar.svg",
    ".ical": "calendar.svg",
    ".jpg": "image.svg",
    ".jpeg": "image.svg",
    ".jpe": "image.svg",
    ".png": "image.svg",
    ".gif": "image.svg",
    ".webp": "image.svg",
    ".avif": "image.svg",
    ".bmp": "image.svg",
    ".tif": "image.svg",
    ".tiff": "image.svg",
    ".heic": "image.svg",
    ".heif": "image.svg",
    ".ico": "image.svg",
    ".jxl": "image.svg",
    ".svg": "vector-image.svg",
    ".svgz": "vector-image.svg",
    ".eps": "drawing.svg",
    ".ai": "drawing.svg",
    ".psd": "drawing.svg",
    ".xcf": "drawing.svg",
    ".kra": "drawing.svg",
    ".mp3": "audio.svg",
    ".wav": "audio.svg",
    ".flac": "audio.svg",
    ".aac": "audio.svg",
    ".ogg": "audio.svg",
    ".oga": "audio.svg",
    ".opus": "audio.svg",
    ".m4a": "audio.svg",
    ".wma": "audio.svg",
    ".mid": "midi.svg",
    ".midi": "midi.svg",
    ".mp4": "video.svg",
    ".m4v": "video.svg",
    ".mkv": "video.svg",
    ".webm": "video.svg",
    ".avi": "video.svg",
    ".mov": "video.svg",
    ".wmv": "video.svg",
    ".flv": "video.svg",
    ".ogv": "video.svg",
    ".mpeg": "video.svg",
    ".mpg": "video.svg",
    ".3gp": "video.svg",
    ".woff": "font.svg",
    ".woff2": "font.svg",
    ".ttf": "font.svg",
    ".otf": "font.svg",
    ".eot": "font.svg",
    ".iso": "iso.svg",
    ".img": "iso.svg",
    ".dmg": "iso.svg",
    ".vhd": "iso.svg",
    ".vhdx": "iso.svg",
    ".qcow": "iso.svg",
    ".qcow2": "iso.svg",
    ".raw": "iso.svg",
    ".pem": "pem-key.svg",
    ".crt": "pem-key.svg",
    ".cer": "pem-key.svg",
    ".der": "pem-key.svg",
    ".key": "key.svg",
    ".pub": "key.svg",
    ".asc": "crypt.svg",
    ".gpg": "crypt.svg",
    ".pgp": "crypt.svg",
    ".p12": "key.svg",
    ".pfx": "key.svg",
    ".csr": "pem-key.svg",
    ".sig": "crypt.svg",
    ".torrent": "torrent.svg",
}

_LITERAL_FILENAME_ICONS = frozenset({"makefile", "dockerfile", "containerfile"})

FALLBACK_ICON = "unknow.svg"
DIRECTORY_ICON = "folder.svg"

ICON_URL_PREFIX = "/.omega-serv-icons/"
"""Chemin URL reserve (meme statut que `/healthz`, verifie tout en haut
de `route_request()` - voir `application/server/serve_icon.py`) sous
lequel les icones sont servies. Vit ici (domain/, pas application/) pour
que `dirlisting.py` (domain, ne peut pas dependre de application/) et
`serve_icon.py` (application) partagent la MEME valeur sans jamais
diverger."""

ICON_FILENAMES: frozenset[str] = (
    frozenset(MIME_ICONS.values()) | frozenset(EXTENSION_ICONS.values()) | {FALLBACK_ICON, DIRECTORY_ICON}
)
"""Ensemble FERME des noms de fichiers icone valides - la seule
"allowlist" que `application/server/serve_icon.py` consulte pour decider
si une requete peut etre servie, jamais une resolution de chemin."""


def icon_for_file(name: str, mime_type: str | None = None, is_directory: bool = False) -> str:
    """Nom de fichier icone (dans `ICON_FILENAMES`) pour l'entree `name`
    d'un directory listing. `mime_type` optionnel et volontairement non
    utilise par l'appelant actuel (dirlisting.py) : la table MIME de
    `domain/http/mime_types.py` est deliberement fermee et etroite
    (19 extensions, pensee pour l'en-tete `Content-Type` reel, jamais
    pour deviner un type) - la lui faire jouer ce role renverrait
    `application/octet-stream` pour la quasi-totalite des fichiers (ex.
    `.py`, `.zip`, `.deb`), qui correspond LUI-MEME a `unknow.svg` dans
    `MIME_ICONS` : predure l'etape d'extension pour presque tout. Le
    parametre reste expose pour un appelant futur dispose d'une
    detection MIME plus large (magic bytes, etc.)."""
    if is_directory:
        return DIRECTORY_ICON

    if mime_type:
        icon = MIME_ICONS.get(mime_type)
        if icon:
            return icon

    path = PurePosixPath(name)
    suffixes = path.suffixes
    for combined in (
        "".join(suffixes[-3:]).lower(),
        "".join(suffixes[-2:]).lower(),
        path.suffix.lower(),
    ):
        if combined in EXTENSION_ICONS:
            return EXTENSION_ICONS[combined]

    if path.name.lower() in _LITERAL_FILENAME_ICONS:
        return "script.svg"

    return FALLBACK_ICON
