"""Page d'erreur HTML par defaut (retour utilisateur 2026-09-09 : "on
mettra des pages html d'erreur fournies de base"). Toujours utilisee
pour toute reponse d'erreur (statut >= 400) dont le corps est vide -
voir infrastructure/server/asyncio_server.py::_write_response, seul
point d'injection (jamais chaque gestionnaire individuellement) - et
seulement si l'option `error_pages` n'est pas activee/configuree pour
ce statut (sinon `resolve_error_page_body` sert le fichier personnalise
de l'utilisateur en priorite, voir application/server/resolve_error_page.py).

Generation en chaine pure, meme convention que
domain/routing/dirlisting.py : jinja2 est confine a
infrastructure.exporters.html_exporter par contrat import-linter, et
une page d'erreur (rendue a chaque requete, potentiellement sous
charge) n'a pas besoin d'un moteur de template pour un contenu aussi
simple.

`_CURATED_PAGES` (401/403/404/451, retour utilisateur 2026-09-19) :
modeles fournis directement en constantes - jamais lues depuis un
fichier (aucune I/O ici, meme regle que le reste du module). Les autres
codes gardent la page generique minimaliste ci-dessous."""
from __future__ import annotations

from html import escape

from omega_serv.domain.http.status_codes import reason_phrase_for

_CURATED_PAGES: dict[int, bytes] = {
    401: (
        "<!DOCTYPE html>\n"
        "<html lang=\"fr\">\n"
        "<head>\n"
        "    <meta charset=\"UTF-8\">\n"
        "    <title>401 - Non autorisé</title>\n"
        "    \t<link rel=\"icon\" type=\"image/png\" href=\"/favicon-96x96.png\" sizes=\"96x96\" />\n"
        "\t<link rel=\"icon\" type=\"image/svg+xml\" href=\"/favicon.svg\" />\n"
        "\t<link rel=\"shortcut icon\" href=\"/favicon.ico\" />\n"
        "\t<link rel=\"apple-touch-icon\" sizes=\"180x180\" href=\"/apple-touch-icon.png\" />\n"
        "\t<meta name=\"apple-mobile-web-app-title\" content=\"Omega\" />\n"
        "    <style>\n"
        "        * { margin: 0; padding: 0; box-sizing: border-box; }\n"
        "        body {\n"
        "            background: #0a0e1a;\n"
        "            color: #e0e0e0;\n"
        "            font-family: monospace;\n"
        "            min-height: 100vh;\n"
        "            display: flex;\n"
        "            justify-content: center;\n"
        "            align-items: center;\n"
        "            padding: 20px;\n"
        "        }\n"
        "        .container {\n"
        "            background: #0f1320;\n"
        "            border-radius: 12px;\n"
        "            padding: 40px;\n"
        "            text-align: center;\n"
        "            max-width: 500px;\n"
        "            box-shadow: 0 8px 32px rgba(0,0,0,0.4);\n"
        "            border: 1px solid rgba(255, 68, 68, 0.3);\n"
        "        }\n"
        "        .code { \n"
        "            font-size: 5rem; \n"
        "            color: #ff4444; \n"
        "            font-weight: bold; \n"
        "            text-shadow: 0 0 10px rgba(255, 68, 68, 0.3);\n"
        "        }\n"
        "        .title { \n"
        "            font-size: 1.5rem; \n"
        "            margin: 20px 0; \n"
        "            color: #ff6666;\n"
        "        }\n"
        "        .msg { \n"
        "            color: #9098a5; \n"
        "            margin-bottom: 30px; \n"
        "        }\n"
        "        .warning {\n"
        "            background: rgba(255, 68, 68, 0.1);\n"
        "            border-left: 3px solid #ff4444;\n"
        "            padding: 12px;\n"
        "            margin: 20px 0;\n"
        "            font-size: 0.85rem;\n"
        "            color: #ff8888;\n"
        "            text-align: left;\n"
        "        }\n"
        "        a { \n"
        "            color: #ff4444; \n"
        "            text-decoration: none; \n"
        "        }\n"
        "        a:hover { \n"
        "            text-decoration: underline; \n"
        "            color: #ff7777;\n"
        "        }\n"
        "        hr { \n"
        "            border: none; \n"
        "            height: 1px; \n"
        "            background: #2a2e3a; \n"
        "            margin: 20px 0; \n"
        "        }\n"
        "        .footer { \n"
        "            font-size: 0.7rem; \n"
        "            color: #606878; \n"
        "            margin-top: 20px; \n"
        "        }\n"
        "    </style>\n"
        "</head>\n"
        "<body>\n"
        "    <div class=\"container\">\n"
        "        <div class=\"code\">401</div>\n"
        "        <div class=\"title\">⛔ Non autorisé</div>\n"
        "        <div class=\"msg\">Authentification requise pour accéder à cette ressource.</div>\n"
        "        <div class=\"warning\">\n"
        "             ✕ Identifiants invalides ou manquants.<br>\n"
        "            Veuillez vérifier vos informations d'accès.\n"
        "        </div>\n"
        "        <hr>\n"
        "         <a href=\"/\">← Retour à l'index</a>\n"
        "        <div class=\"footer\">  ⚡ propulsé par <a href=\"https://github.com/kraynux/omega-serv\">OMEGA-SERV</a></div>\n"
        "    </div>\n"
        "</body>\n"
        "</html>\n"
    ).encode(),
    403: (
        "<!DOCTYPE html>\n"
        "<html lang=\"fr\">\n"
        "<head>\n"
        "    <meta charset=\"UTF-8\">\n"
        "    <title>403 - Accès interdit</title>\n"
        "    \t<link rel=\"icon\" type=\"image/png\" href=\"/favicon-96x96.png\" sizes=\"96x96\" />\n"
        "\t<link rel=\"icon\" type=\"image/svg+xml\" href=\"/favicon.svg\" />\n"
        "\t<link rel=\"shortcut icon\" href=\"/favicon.ico\" />\n"
        "\t<link rel=\"apple-touch-icon\" sizes=\"180x180\" href=\"/apple-touch-icon.png\" />\n"
        "\t<meta name=\"apple-mobile-web-app-title\" content=\"Omega\" />\n"
        "    <style>\n"
        "        * { margin: 0; padding: 0; box-sizing: border-box; }\n"
        "        body {\n"
        "            background: #0a0e1a;\n"
        "            color: #e0e0e0;\n"
        "            font-family: monospace;\n"
        "            min-height: 100vh;\n"
        "            display: flex;\n"
        "            justify-content: center;\n"
        "            align-items: center;\n"
        "            padding: 20px;\n"
        "        }\n"
        "        .container {\n"
        "            background: #0f1320;\n"
        "            border-radius: 12px;\n"
        "            padding: 40px;\n"
        "            text-align: center;\n"
        "            max-width: 500px;\n"
        "            box-shadow: 0 8px 32px rgba(0,0,0,0.4);\n"
        "            border: 1px solid rgba(255, 170, 68, 0.8);\n"
        "        }\n"
        "        .code { \n"
        "            font-size: 5rem; \n"
        "            color: #ffaa44; \n"
        "            font-weight: bold; \n"
        "            text-shadow: 0 0 10px rgba(255, 170, 68, 0.3);\n"
        "        }\n"
        "        .title { \n"
        "            font-size: 1.5rem; \n"
        "            margin: 20px 0; \n"
        "            color: #ffbb66;\n"
        "        }\n"
        "        .msg { \n"
        "            color: #9098a5; \n"
        "            margin-bottom: 30px; \n"
        "        }\n"
        "        .warning {\n"
        "            background: rgba(255, 170, 68, 0.1);\n"
        "            border-left: 3px solid #ffaa44;\n"
        "            padding: 12px;\n"
        "            margin: 20px 0;\n"
        "            font-size: 0.85rem;\n"
        "            color: #ffcc88;\n"
        "            text-align: left;\n"
        "        }\n"
        "        a { \n"
        "            color: #ffaa44; \n"
        "            text-decoration: none; \n"
        "        }\n"
        "        a:hover { \n"
        "            text-decoration: underline; \n"
        "            color: #ffcc88;\n"
        "        }\n"
        "        hr { \n"
        "            border: none; \n"
        "            height: 1px; \n"
        "            background: #2a2e3a; \n"
        "            margin: 20px 0; \n"
        "        }\n"
        "        .footer { \n"
        "            font-size: 0.7rem; \n"
        "            color: #606878; \n"
        "            margin-top: 20px; \n"
        "        }\n"
        "    </style>\n"
        "</head>\n"
        "<body>\n"
        "    <div class=\"container\">\n"
        "        <div class=\"code\">403</div>\n"
        "        <div class=\"title\">⛔ Accès interdit</div>\n"
        "        <div class=\"msg\">Vous n'avez pas les droits nécessaires pour accéder à cette ressource.</div>\n"
        "        <div class=\"warning\">\n"
        "             \t        Permission refusée.<br>\n"
        "            Vérifiez vos droits d'accès ou contactez l'administrateur.\n"
        "        </div>\n"
        "        <hr>\n"
        "        <a href=\"/\">← Retour à l'index</a>\n"
        "        <div class=\"footer\">  ⚡ propulsé par <a href=\"https://github.com/kraynux/omega-serv\">OMEGA-SERV</a></div>\n"
        "    </div>\n"
        "</body>\n"
        "</html>\n"
    ).encode(),
    404: (
        "<!DOCTYPE html>\n"
        "<html lang=\"fr\">\n"
        "<head>\n"
        "    <meta charset=\"UTF-8\">\n"
        "    <title>404 - Page non trouvée</title>\n"
        "    \t<link rel=\"icon\" type=\"image/png\" href=\"/favicon-96x96.png\" sizes=\"96x96\" />\n"
        "\t<link rel=\"icon\" type=\"image/svg+xml\" href=\"/favicon.svg\" />\n"
        "\t<link rel=\"shortcut icon\" href=\"/favicon.ico\" />\n"
        "\t<link rel=\"apple-touch-icon\" sizes=\"180x180\" href=\"/apple-touch-icon.png\" />\n"
        "\t<meta name=\"apple-mobile-web-app-title\" content=\"Omega\" />\n"
        "    <style>\n"
        "        * { margin: 0; padding: 0; box-sizing: border-box; }\n"
        "        body {\n"
        "            background: #0a0e1a;\n"
        "            color: #e0e0e0;\n"
        "            font-family: monospace;\n"
        "            min-height: 100vh;\n"
        "            display: flex;\n"
        "            justify-content: center;\n"
        "            align-items: center;\n"
        "            padding: 20px;\n"
        "        }\n"
        "        .container {\n"
        "            background: #0f1320;\n"
        "            border-radius: 12px;\n"
        "            padding: 40px;\n"
        "            text-align: center;\n"
        "            max-width: 500px;\n"
        "            box-shadow: 0 8px 32px rgba(0,0,0,0.4);\n"
        "            border: 1px solid rgba(0, 212, 255, 0.9);\n"
        "        }\n"
        "        .code { font-size: 5rem; color: #00d4ff; font-weight: bold; }\n"
        "        .title { font-size: 1.5rem; margin: 20px 0; }\n"
        "        .msg { color: #9098a5; margin-bottom: 30px; }\n"
        "        .warning {\n"
        "            background: rgba(0, 212, 255, 0.08);\n"
        "            border-left: 3px solid #00d4ff;\n"
        "            padding: 12px;\n"
        "            margin: 20px 0;\n"
        "            font-size: 0.85rem;\n"
        "            color: #9098a5;\n"
        "            text-align: left;\n"
        "        }\n"
        "        a { color: #00d4ff; text-decoration: none; }\n"
        "        a:hover { text-decoration: underline; }\n"
        "        hr { border: none; height: 1px; background: #2a2e3a; margin: 20px 0; }\n"
        "        .footer { font-size: 0.7rem; color: #606878; margin-top: 20px; }\n"
        "    </style>\n"
        "</head>\n"
        "<body>\n"
        "    <div class=\"container\">\n"
        "        <div class=\"code\">404</div>\n"
        "        <div class=\"title\">✖   Page non trouvée</div>\n"
        "        <div class=\"msg\">La ressource demandée n'existe pas ou a été déplacée</div>\n"
        "        <div class=\"warning\">\n"
        "            Verifier l'adresse url dans la barre d'adresse.<br>\n"
        "\n"
        "        </div>\n"
        "        <hr>\n"
        "        <a href=\"/\">← Retour à l'index</a>\n"
        "        <div class=\"footer\">  ⚡ propulsé par <a href=\"https://github.com/kraynux/omega-serv\">OMEGA-SERV</a></div>\n"
        "    </div>\n"
        "</body>\n"
        "</html>\n"
    ).encode(),
    451: (
        "<!DOCTYPE html>\n"
        "<html lang=\"fr\">\n"
        "<head>\n"
        "    <meta charset=\"UTF-8\">\n"
        "    <link rel=\"icon\" type=\"image/png\" href=\"/favicon-96x96.png\" sizes=\"96x96\" />\n"
        "<link rel=\"icon\" type=\"image/svg+xml\" href=\"/favicon.svg\" />\n"
        "<link rel=\"shortcut icon\" href=\"/favicon.ico\" />\n"
        "<link rel=\"apple-touch-icon\" sizes=\"180x180\" href=\"/apple-touch-icon.png\" />\n"
        "<meta name=\"apple-mobile-web-app-title\" content=\"Omega\" />\n"
        "    <title>451 - Accès interdit</title>\n"
        "     <style>\n"
        "        * { margin: 0; padding: 0; box-sizing: border-box; }\n"
        "        body {\n"
        "            background: #0a0e1a;\n"
        "            color: #e0e0e0;\n"
        "            font-family: monospace;\n"
        "            min-height: 100vh;\n"
        "            display: flex;\n"
        "            justify-content: center;\n"
        "            align-items: center;\n"
        "            padding: 20px;\n"
        "        }\n"
        "        .container {\n"
        "            background: #0f1320;\n"
        "            border-radius: 12px;\n"
        "            padding: 40px;\n"
        "            text-align: center;\n"
        "            max-width: 500px;\n"
        "            box-shadow: 0 8px 32px rgba(0,0,0,0.4);\n"
        "            border: 1px solid rgba(255, 68, 68, 0.3);\n"
        "        }\n"
        "        .code { \n"
        "            font-size: 5rem; \n"
        "            color: #ff4444; \n"
        "            font-weight: bold; \n"
        "            text-shadow: 0 0 10px rgba(255, 68, 68, 0.3);\n"
        "        }\n"
        "        .title { \n"
        "            font-size: 1.5rem; \n"
        "            margin: 20px 0; \n"
        "            color: #ff6666;\n"
        "        }\n"
        "        .msg { \n"
        "            color: #9098a5; \n"
        "            margin-bottom: 30px; \n"
        "        }\n"
        "        .warning {\n"
        "            background: rgba(255, 68, 68, 0.1);\n"
        "            border-left: 3px solid #ff4444;\n"
        "            padding: 12px;\n"
        "            margin: 20px 0;\n"
        "            font-size: 0.85rem;\n"
        "            color: #ff8888;\n"
        "            text-align: left;\n"
        "        }\n"
        "        a { \n"
        "            color: #ff4444; \n"
        "            text-decoration: none; \n"
        "        }\n"
        "        a:hover { \n"
        "            text-decoration: underline; \n"
        "            color: #ff7777;\n"
        "        }\n"
        "        hr { \n"
        "            border: none; \n"
        "            height: 1px; \n"
        "            background: #2a2e3a; \n"
        "            margin: 20px 0; \n"
        "        }\n"
        "        .footer { \n"
        "            font-size: 0.7rem; \n"
        "            color: #606878; \n"
        "            margin-top: 20px; \n"
        "        }\n"
        "    </style>\n"
        "</head>\n"
        "<body>\n"
        "    <div class=\"container\">\n"
        "        <div class=\"code\">451</div>\n"
        "\n"
        "        <div class=\"title\">🕱 Votre IP a été bannie</div>\n"
        "        <p class=\"msg\">Durée entre 1 minute et 1 année selon le type de requete que vous avez effectué !</p>\n"
        "\n"
        "        <p class=\"warning\">● Si vous pensez qu'il s'agit d'une erreur, contactez l'administrateur du site</p> <hr>\n"
        "        <p class=\"msg\"><a href=\"https://www.google.com\">← Retourner sur Google en attendant :-) </a></p>\n"
        "        <div class=\"footer\">⚡ propulsé par <a href=\"https://github.com/kraynux/omega-serv\">OMEGA-SERV</a></div>\n"
        "    </div>\n"
        "</body>\n"
        "</html>\n"
    ).encode(),
}


def render_default_error_page(status: int) -> bytes:
    curated = _CURATED_PAGES.get(status)
    if curated is not None:
        return curated
    reason = reason_phrase_for(status) or "Erreur"
    title = escape(f"{status} {reason}")
    return (
        "<!doctype html><html lang=\"fr\"><head><meta charset=\"utf-8\">"
        f"<title>{title}</title>"
        "<style>"
        "body{font-family:ui-monospace,Consolas,monospace;background:#0a0e1a;"
        "color:#e0e0e0;display:flex;align-items:center;justify-content:center;"
        "height:100vh;margin:0}"
        ".box{text-align:center}"
        "h1{font-size:2.5rem;margin:0 0 .5rem;color:#00d4ff}"
        "p{color:#b4c2e0;margin:0}"
        "</style></head><body><div class=\"box\">"
        f"<h1>{status}</h1><p>{escape(reason)}</p>"
        "</div></body></html>"
    ).encode()
